"""Contact domain (Outreach context): independent aggregate root (ADR-0022)."""

from app.domain.contact.aggregate import Contact
from app.domain.contact.roles import (
    ROLE_DEFINITIONS,
    ROLES_BY_CODE,
    TAXONOMY_VERSION,
    DecisionRole,
    RoleDefinition,
    decision_relevance,
    legacy_department,
    role_definition,
    roles_from_legacy_department,
)
from app.domain.contact.values import (
    ContactChannel,
    ContactChannelType,
    ContactMatch,
    ContactMatchKind,
    ContactStatus,
    ContactVerificationStatus,
    DecisionMakerFitAssessment,
    Department,
    JobTitle,
    PersonName,
    RawContactSnapshot,
    SelectionThresholds,
    SeniorityLevel,
)

__all__ = [
    "ROLES_BY_CODE",
    "ROLE_DEFINITIONS",
    "TAXONOMY_VERSION",
    "DecisionRole",
    "RoleDefinition",
    "decision_relevance",
    "legacy_department",
    "role_definition",
    "roles_from_legacy_department",
    "Contact",
    "ContactChannel",
    "ContactChannelType",
    "ContactMatch",
    "ContactMatchKind",
    "ContactStatus",
    "ContactVerificationStatus",
    "DecisionMakerFitAssessment",
    "Department",
    "JobTitle",
    "PersonName",
    "RawContactSnapshot",
    "SelectionThresholds",
    "SeniorityLevel",
]
