"""add import evidence snapshots table

Revision ID: 000f9f538d31
Revises: 54b3de20fb09
Create Date: 2026-07-21 01:31:08.741454

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '000f9f538d31'
down_revision: str | None = '54b3de20fb09'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_evidence_conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('signal_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conflict_type', sa.String(length=100), nullable=False),
    sa.Column('conflict_detail', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_evidence_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('total_raw', sa.Integer(), nullable=False),
    sa.Column('total_normalized', sa.Integer(), nullable=False),
    sa.Column('total_deduped', sa.Integer(), nullable=False),
    sa.Column('total_matched', sa.Integer(), nullable=False),
    sa.Column('total_promoted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','completed','partial','failed','needs_review')", name='ck_evidence_job_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_jobs_company', 'import_evidence_jobs', ['company_id'], unique=False)
    op.create_table('import_evidence_raw_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_record_id', sa.String(length=200), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('raw_payload_json', sa.Text(), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('fixture', sa.Boolean(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_evidence_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_record_id', 'raw_payload_hash', name='uq_raw_record_dedup')
    )
    op.create_index('ix_raw_records_job', 'import_evidence_raw_records', ['job_id'], unique=False)
    op.create_index('ix_raw_records_provider', 'import_evidence_raw_records', ['provider'], unique=False)
    op.create_table('import_evidence_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('raw_record_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_shipment_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aggregation_window', sa.String(length=50), nullable=False),
    sa.Column('calculation_method', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('quality_level', sa.String(length=10), nullable=False),
    sa.Column('entity_match_method', sa.String(length=20), nullable=False),
    sa.Column('entity_match_score', sa.Float(), nullable=False),
    sa.Column('promotion_version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['import_evidence_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_signals_company', 'import_evidence_signals', ['company_id'], unique=False)
    op.create_table('import_evidence_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('snapshot_version', sa.String(length=10), nullable=False),
    sa.Column('raw_count', sa.Integer(), nullable=False),
    sa.Column('normalized_count', sa.Integer(), nullable=False),
    sa.Column('deduped_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('promoted_count', sa.Integer(), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['import_evidence_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_snapshots_company', 'import_evidence_snapshots', ['company_id'], unique=False)
    op.create_index('ix_evidence_snapshots_job', 'import_evidence_snapshots', ['job_id'], unique=False)
    op.create_table('normalized_shipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('importer_name', sa.String(length=300), nullable=False),
    sa.Column('importer_address', sa.Text(), nullable=False),
    sa.Column('normalized_importer', sa.String(length=300), nullable=False),
    sa.Column('shipper_name', sa.String(length=300), nullable=False),
    sa.Column('shipper_country', sa.String(length=2), nullable=False),
    sa.Column('country_of_origin', sa.String(length=2), nullable=False),
    sa.Column('arrival_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('port_of_lading', sa.String(length=100), nullable=False),
    sa.Column('port_of_discharge', sa.String(length=100), nullable=False),
    sa.Column('master_bol', sa.String(length=50), nullable=False),
    sa.Column('house_bol', sa.String(length=50), nullable=False),
    sa.Column('carrier_scac', sa.String(length=10), nullable=False),
    sa.Column('vessel', sa.String(length=100), nullable=False),
    sa.Column('voyage', sa.String(length=20), nullable=False),
    sa.Column('container_numbers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('teu', sa.Float(), nullable=True),
    sa.Column('hs_codes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('goods_description_raw', sa.Text(), nullable=False),
    sa.Column('goods_description_normalized', sa.Text(), nullable=False),
    sa.Column('value_amount', sa.Float(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_record_id', sa.String(length=200), nullable=False),
    sa.Column('shipment_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('dedupe_method', sa.String(length=20), nullable=False),
    sa.Column('dedupe_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_record_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_evidence_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_fingerprint', name='uq_shipment_fingerprint')
    )
    op.create_index('ix_shipments_arrival', 'normalized_shipments', ['arrival_date'], unique=False)
    op.create_index('ix_shipments_importer', 'normalized_shipments', ['normalized_importer'], unique=False)
    op.create_table('importer_entity_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('match_method', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_company_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['normalized_shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('importer_entity_matches')
    op.drop_index('ix_shipments_importer', table_name='normalized_shipments')
    op.drop_index('ix_shipments_arrival', table_name='normalized_shipments')
    op.drop_table('normalized_shipments')
    op.drop_index('ix_evidence_snapshots_job', table_name='import_evidence_snapshots')
    op.drop_index('ix_evidence_snapshots_company', table_name='import_evidence_snapshots')
    op.drop_table('import_evidence_snapshots')
    op.drop_index('ix_evidence_signals_company', table_name='import_evidence_signals')
    op.drop_table('import_evidence_signals')
    op.drop_index('ix_raw_records_provider', table_name='import_evidence_raw_records')
    op.drop_index('ix_raw_records_job', table_name='import_evidence_raw_records')
    op.drop_table('import_evidence_raw_records')
    op.drop_index('ix_evidence_jobs_company', table_name='import_evidence_jobs')
    op.drop_table('import_evidence_jobs')
    op.drop_table('import_evidence_conflicts')
    # ### end Alembic commands ###
