"""shipment normalization fields: fingerprint version, dedupe, weight scope, parent

Revision ID: 0d4c02e927a7
Revises: 000f9f538d31
Create Date: 2026-07-21 01:46:08.853450

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0d4c02e927a7'
down_revision: str | None = '000f9f538d31'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normalized_shipments', sa.Column('fingerprint_version', sa.String(length=20), nullable=False))
    op.add_column('normalized_shipments', sa.Column('dedupe_status', sa.String(length=30), nullable=False))
    op.add_column('normalized_shipments', sa.Column('container_count', sa.Integer(), nullable=False))
    op.add_column('normalized_shipments', sa.Column('raw_weight', sa.Float(), nullable=True))
    op.add_column('normalized_shipments', sa.Column('raw_weight_unit', sa.String(length=10), nullable=False))
    op.add_column('normalized_shipments', sa.Column('normalized_weight', sa.Float(), nullable=True))
    op.add_column('normalized_shipments', sa.Column('normalized_weight_unit', sa.String(length=10), nullable=False))
    op.add_column('normalized_shipments', sa.Column('weight_scope', sa.String(length=20), nullable=False))
    op.add_column('normalized_shipments', sa.Column('raw_quantity', sa.Float(), nullable=True))
    op.add_column('normalized_shipments', sa.Column('normalized_quantity', sa.Float(), nullable=True))
    op.add_column('normalized_shipments', sa.Column('parent_shipment_id', sa.Uuid(), nullable=True))
    op.add_column('normalized_shipments', sa.Column('normalization_version', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('normalized_shipments', 'normalization_version')
    op.drop_column('normalized_shipments', 'parent_shipment_id')
    op.drop_column('normalized_shipments', 'normalized_quantity')
    op.drop_column('normalized_shipments', 'raw_quantity')
    op.drop_column('normalized_shipments', 'weight_scope')
    op.drop_column('normalized_shipments', 'normalized_weight_unit')
    op.drop_column('normalized_shipments', 'normalized_weight')
    op.drop_column('normalized_shipments', 'raw_weight_unit')
    op.drop_column('normalized_shipments', 'raw_weight')
    op.drop_column('normalized_shipments', 'container_count')
    op.drop_column('normalized_shipments', 'dedupe_status')
    op.drop_column('normalized_shipments', 'fingerprint_version')
    # ### end Alembic commands ###
