"""assessment fingerprint, completeness, qualification, breakdown

Revision ID: 1d123ee886aa
Revises: eaef5d33aa6a
Create Date: 2026-07-16 02:36:59.944110

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1d123ee886aa'
down_revision: str | None = 'eaef5d33aa6a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_assessments', sa.Column('data_completeness', sa.Float(), nullable=True))
    op.add_column('opportunity_assessments', sa.Column('qualification_decision', sa.String(length=20), nullable=True))
    op.add_column('opportunity_assessments', sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('opportunity_assessments', sa.Column('assessment_fingerprint', sa.String(length=64), nullable=False))
    op.add_column('opportunity_assessments', sa.Column('policy_version', sa.String(length=50), server_default='unversioned', nullable=False))
    op.create_unique_constraint('uq_assessments_fingerprint', 'opportunity_assessments', ['opportunity_id', 'assessment_fingerprint'])
    # check constraints are not autogenerated — added manually (L9)
    op.create_check_constraint(
        'ck_assessments_completeness_range',
        'opportunity_assessments',
        'data_completeness IS NULL OR (data_completeness >= 0 AND data_completeness <= 1)',
    )
    op.create_check_constraint(
        'ck_assessments_qualification_controlled',
        'opportunity_assessments',
        "qualification_decision IS NULL OR qualification_decision IN "
        "('qualified', 'review', 'research_more', 'disqualified')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_assessments_qualification_controlled', 'opportunity_assessments', type_='check')
    op.drop_constraint('ck_assessments_completeness_range', 'opportunity_assessments', type_='check')
    op.drop_constraint('uq_assessments_fingerprint', 'opportunity_assessments', type_='unique')
    op.drop_column('opportunity_assessments', 'policy_version')
    op.drop_column('opportunity_assessments', 'assessment_fingerprint')
    op.drop_column('opportunity_assessments', 'score_breakdown')
    op.drop_column('opportunity_assessments', 'qualification_decision')
    op.drop_column('opportunity_assessments', 'data_completeness')
    # ### end Alembic commands ###
