"""import evidence agent: raw records, normalized shipments, entity matches, signals, conflicts

Revision ID: 54b3de20fb09
Revises: 9d9f7576a7ac
Create Date: 2026-07-21 01:20:25.679568

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '54b3de20fb09'
down_revision: str | None = '9d9f7576a7ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
