"""initial schema: four aggregates

Revision ID: 85d4b54db359
Revises: 
Create Date: 2026-07-15 23:17:25.042434

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '85d4b54db359'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('website_host', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_website_host', 'companies', ['website_host'], unique=False)
    op.create_index('uq_companies_normalized_name', 'companies', ['normalized_name'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_tasks_attempts_non_negative'),
    sa.CheckConstraint('max_retries >= 0', name='ck_tasks_max_retries_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('uq_tasks_active_idempotency_key', 'tasks', ['idempotency_key'], unique=True, postgresql_where="status IN ('created', 'running')")
    op.create_table('company_aliases',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'normalized_name')
    )
    op.create_table('company_signals',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('signal', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'position')
    )
    op.create_table('company_sources',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'position')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_company_id', 'contacts', ['company_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('stage_reason', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_opportunities_confidence_range'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_opportunities_score_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_company_id', 'opportunities', ['company_id'], unique=False)
    op.create_index('ix_opportunities_priority', 'opportunities', ['priority'], unique=False)
    op.create_index('ix_opportunities_stage', 'opportunities', ['stage'], unique=False)
    op.create_index('ix_opportunities_user_id', 'opportunities', ['user_id'], unique=False)
    op.create_table('task_attempts',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'number')
    )
    op.create_table('opportunity_assessments',
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('old_score', sa.Float(), nullable=True),
    sa.Column('new_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring_version', sa.String(length=50), nullable=False),
    sa.Column('user_lens_version', sa.String(length=50), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_assessments_confidence_range'),
    sa.CheckConstraint('new_score >= 0 AND new_score <= 100', name='ck_assessments_new_score_range'),
    sa.CheckConstraint('old_score IS NULL OR (old_score >= 0 AND old_score <= 100)', name='ck_assessments_old_score_range'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id', 'position')
    )
    op.create_table('outreaches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_version', sa.Integer(), nullable=True),
    sa.Column('sent_version', sa.Integer(), nullable=True),
    sa.Column('follow_up_active', sa.Boolean(), nullable=False),
    sa.Column('closed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outreaches_opportunity_id', 'outreaches', ['opportunity_id'], unique=False)
    op.create_index('ix_outreaches_status', 'outreaches', ['status'], unique=False)
    op.create_table('email_drafts',
    sa.Column('outreach_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreaches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outreach_id', 'version')
    )
    op.create_table('opportunity_evidence',
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_position', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id', 'assessment_position'], ['opportunity_assessments.opportunity_id', 'opportunity_assessments.position'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id', 'assessment_position', 'position')
    )
    op.create_table('outcomes',
    sa.Column('outreach_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('draft_version', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreaches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outreach_id', 'position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcomes')
    op.drop_table('opportunity_evidence')
    op.drop_table('email_drafts')
    op.drop_index('ix_outreaches_status', table_name='outreaches')
    op.drop_index('ix_outreaches_opportunity_id', table_name='outreaches')
    op.drop_table('outreaches')
    op.drop_table('opportunity_assessments')
    op.drop_table('task_attempts')
    op.drop_index('ix_opportunities_user_id', table_name='opportunities')
    op.drop_index('ix_opportunities_stage', table_name='opportunities')
    op.drop_index('ix_opportunities_priority', table_name='opportunities')
    op.drop_index('ix_opportunities_company_id', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('ix_contacts_company_id', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('company_sources')
    op.drop_table('company_signals')
    op.drop_table('company_aliases')
    op.drop_index('uq_tasks_active_idempotency_key', table_name='tasks', postgresql_where="status IN ('created', 'running')")
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('uq_companies_normalized_name', table_name='companies')
    op.drop_index('ix_companies_website_host', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
