"""persist decision maker scoring evidence v2

Revision ID: 9d9f7576a7ac
Revises: e51b7c3d84af
Create Date: 2026-07-20 23:45:36.740637

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9d9f7576a7ac'
down_revision: str | None = 'e51b7c3d84af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_fit_assessments', sa.Column('score_breakdown_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('contact_fit_assessments', sa.Column('selection_status', sa.String(length=30), nullable=True))
    op.add_column('contact_fit_assessments', sa.Column('selection_reasons_json', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('contact_fit_assessments', sa.Column('scoring_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_fit_assessments', 'scoring_version')
    op.drop_column('contact_fit_assessments', 'selection_reasons_json')
    op.drop_column('contact_fit_assessments', 'selection_status')
    op.drop_column('contact_fit_assessments', 'score_breakdown_json')
    # ### end Alembic commands ###
