"""contact aggregate: channels, sources, fit assessments

Revision ID: c4470047a477
Revises: 1d123ee886aa
Create Date: 2026-07-16 03:05:44.966949

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c4470047a477'
down_revision: str | None = '1d123ee886aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_channels',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('normalized_value', sa.String(length=320), nullable=False),
    sa.Column('display_value', sa.String(length=320), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.CheckConstraint("channel_type IN ('email', 'linkedin', 'phone')", name='ck_channels_type_controlled'),
    sa.CheckConstraint("verification_status IN ('unverified', 'source_verified', 'manually_verified', 'invalid')", name='ck_channels_verification_controlled'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_channels_confidence_range'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'channel_type', 'normalized_value')
    )
    op.create_table('contact_fit_assessments',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('role_fit_score', sa.Float(), nullable=False),
    sa.Column('reachability_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.Column('seniority', sa.String(length=20), nullable=False),
    sa.Column('recommended_channel', sa.String(length=20), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_fit_confidence_range'),
    sa.CheckConstraint('reachability_score >= 0 AND reachability_score <= 100', name='ck_fit_reachability_range'),
    sa.CheckConstraint('role_fit_score >= 0 AND role_fit_score <= 100', name='ck_fit_role_score_range'),
    sa.CheckConstraint('total_score >= 0 AND total_score <= 100', name='ck_fit_total_range'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'assessment_fingerprint')
    )
    op.create_index('ix_fit_assessments_company_id', 'contact_fit_assessments', ['company_id'], unique=False)
    op.create_table('contact_sources',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'position')
    )
    op.add_column('contacts', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('contacts', sa.Column('normalized_name', sa.String(length=200), nullable=False))
    op.add_column('contacts', sa.Column('title_raw', sa.String(length=200), nullable=True))
    op.add_column('contacts', sa.Column('department', sa.String(length=20), nullable=False))
    op.add_column('contacts', sa.Column('seniority', sa.String(length=20), nullable=False))
    op.add_column('contacts', sa.Column('invalid_reason', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('ix_contacts_status', 'contacts', ['status'], unique=False)
    op.drop_column('contacts', 'title')
    op.drop_column('contacts', 'full_name')
    op.drop_column('contacts', 'email')
    # check constraints on the altered table are not autogenerated (L10)
    op.create_check_constraint(
        'ck_contacts_status_controlled',
        'contacts',
        "status IN ('discovered', 'active', 'invalid', 'inactive')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_contacts_status_controlled', 'contacts', type_='check')
    op.add_column('contacts', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index('ix_contacts_status', table_name='contacts')
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'invalid_reason')
    op.drop_column('contacts', 'seniority')
    op.drop_column('contacts', 'department')
    op.drop_column('contacts', 'title_raw')
    op.drop_column('contacts', 'normalized_name')
    op.drop_column('contacts', 'name')
    op.drop_table('contact_sources')
    op.drop_index('ix_fit_assessments_company_id', table_name='contact_fit_assessments')
    op.drop_table('contact_fit_assessments')
    op.drop_table('contact_channels')
    # ### end Alembic commands ###
