"""email draft status, provider, fingerprint

Revision ID: d6ef81dfc959
Revises: c4470047a477
Create Date: 2026-07-16 18:58:46.743120

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd6ef81dfc959'
down_revision: str | None = 'c4470047a477'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_drafts', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('email_drafts', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('email_drafts', sa.Column('model', sa.String(length=100), nullable=False))
    op.add_column('email_drafts', sa.Column('context_fingerprint', sa.String(length=64), nullable=False))
    op.add_column('email_drafts', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('uq_drafts_context_prompt', 'email_drafts', ['outreach_id', 'context_fingerprint', 'prompt_version'], unique=True, postgresql_where="context_fingerprint <> ''")
    op.drop_column('email_drafts', 'created_at')
    # check constraints are not autogenerated — added manually (L11)
    op.create_check_constraint('ck_drafts_subject_not_empty', 'email_drafts', "subject <> ''")
    op.create_check_constraint('ck_drafts_body_not_empty', 'email_drafts', "body <> ''")
    op.create_check_constraint(
        'ck_drafts_status_controlled',
        'email_drafts',
        "status IN ('generated', 'approved', 'rejected')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_drafts_status_controlled', 'email_drafts', type_='check')
    op.drop_constraint('ck_drafts_body_not_empty', 'email_drafts', type_='check')
    op.drop_constraint('ck_drafts_subject_not_empty', 'email_drafts', type_='check')
    op.add_column('email_drafts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index('uq_drafts_context_prompt', table_name='email_drafts', postgresql_where="context_fingerprint <> ''")
    op.drop_column('email_drafts', 'generated_at')
    op.drop_column('email_drafts', 'context_fingerprint')
    op.drop_column('email_drafts', 'model')
    op.drop_column('email_drafts', 'provider')
    op.drop_column('email_drafts', 'status')
    # ### end Alembic commands ###
