"""assessment priority, recommended_action, assessed_by

Revision ID: eaef5d33aa6a
Revises: 85d4b54db359
Create Date: 2026-07-16 01:08:43.309904

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'eaef5d33aa6a'
down_revision: str | None = '85d4b54db359'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_assessments', sa.Column('priority', sa.String(length=10), nullable=True))
    op.add_column('opportunity_assessments', sa.Column('recommended_action', sa.Text(), nullable=True))
    op.add_column('opportunity_assessments', sa.Column('assessed_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_assessments', 'assessed_by')
    op.drop_column('opportunity_assessments', 'recommended_action')
    op.drop_column('opportunity_assessments', 'priority')
    # ### end Alembic commands ###
